Lesson 3
bl1ndy/t-39-test-guru pull request #2
Opened 2022-06-11 22:27 UTC by bl1ndy

2022-06-11 22:29 UTC, bl1ndy commented on config/routes.rb
>  end
Забыл удалить их, когда вносил правки в прошлом уроке

2022-06-13 17:30 UTC, BubuntuClu requested changes

2022-06-13 17:30 UTC, BubuntuClu commented on db/migrate/20220611212340_create_tests.rb
> +
нужно добавить внешний ключ к таблице категорий

2022-06-13 17:30 UTC, BubuntuClu commented on db/migrate/20220611212730_create_questions.rb
> +
нужно добавить внешний ключ к таблице тестов

2022-06-14 09:52 UTC, merged